"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy": true

"files": [
  {
    "source": "Resources/lang/en-GB/general.php",
    "dest": "offline-payments/general.php",
    "translation": "Resources/lang/%locale%/offline-payments/general.php",
    "translation_replace": {
      "offline-payments/": ""
    }
  }
]
