name: Translations

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    name: Sync

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Sync with Crowdin
      uses: crowdin/github-action@master
      with:
        upload_sources: true
        upload_translations: true
        download_translations: true
        skip_untranslated_files: true

        localization_branch_name: 'translations'
        commit_message: 'new crowdin translations'
        pull_request_title: 'New Crowdin translations'
        pull_request_body: 'https://crowdin.com/project/akaunting-apps'
        pull_request_labels: 'Translation'

        config: 'crowdin.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_APPS_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
